### PR TITLE
feat: checkbox to enable options if product is a course

### PR DESCRIPTION
**Pull request by julianramirez2**
## Description

Created a checkbox that allows users to perform a 'double-check' of the product in case it's a course, enabling them to add their course_id and course mode properties.

## Testing instructions

To test it, you should access a WooCommerce product and scroll down to the product options. You will see the new checkbox, and it will be sufficient to check it, uncheck it, and save.

https://github.com/eduNEXT/openedx-woocommerce-plugin/assets/52968528/4ab70bcb-812b-4cb8-bb9e-12101527b4f4

## Additional information

A JavaScript function has been added to control this checkbox, which will always check its state and, depending on it, show or disable the options. This JavaScript is inserted using 'wp_enqueue_script,' which is a WordPress function that processes custom JavaScript files.

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by julianramirez2** [comment]
@MaferMazu @andres-arango-aptitude can you check this, please?

**Comment by julianramirez2** [comment]
I just changed something about how to set if a product is an Open edX Course or not, it is working with a "product type" and not a custom form in general settings. Now the option appears at the top, next to "downloadable" and "virtual" options, and depending if the check is checked or not and validating if the course_id field is different from empty, allows the user or the process to create a new enrollment. It looks like this right now:

https://github.com/eduNEXT/openedx-woocommerce-plugin/assets/52968528/c3f29c0f-f7b1-480e-9eb4-ec0fd7ac7041

**Review by MaferMazu — APPROVED** [review]
Can you add new lines in the files it doesn't have it? The rest looks good to me.

**Comment by julianramirez2** [comment]
> Can you add new lines in the files it doesn't have it? The rest looks good to me.

Done

**Review by MaferMazu — APPROVED** [review]

**Pull request merged**
